// Code generated by pocket. DO NOT EDIT.
// To add custom tasks, add them to Config.Tasks in config.go.
// See: https://github.com/fredrikaverpil/pocket#custom-tasks

package main

import (
	"github.com/fredrikaverpil/pocket"
	"github.com/fredrikaverpil/pocket/tasks"
)

func main() {
	t := tasks.New(Config)
	pocket.Main(t.AllTasks(), t.All)
}
